name: Run Selected Pytest Tests

on:
  workflow_dispatch:
    inputs:
      test_files:
        description: 'Test files to run (space-separated paths)'
        required: true
        default: 'tests/test_api.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run selected tests
      run: |
        echo "Running tests: ${{ github.event.inputs.test_files }}"
        pytest ${{ github.event.inputs.test_files }}
